/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ANT_MiddleWare_jni_udpSend */

#ifndef _Included_com_ANT_MiddleWare_jni_udpSend
#define _Included_com_ANT_MiddleWare_jni_udpSend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ANT_MiddleWare_jni_udpSend
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ANT_MiddleWare_jni_udpSend_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ANT_MiddleWare_jni_udpSend
 * Method:    send
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_ANT_MiddleWare_jni_udpSend_send
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
